# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    steps:
      - checkout
      - run: sudo apt-get install openssl
      - run: sudo apt-get install python3 python-pip python-dev build-essential
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - run: sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) \
                stable"
      - run: apt-cache policy docker-ce && sudo apt-get install -y docker-ce

      - run: sudo pip install pip
      - run: sudo pip install --upgrade virtualenv
      - run: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run: unzip awscli-bundle.zip
      - run: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run: source ~/.bashrc
      - run: aws --version
      - run: npm install
      - run: sudo npm install -g typescript
      - run: printf '%s\n' "ACCESS_KEY_ID=$ACCESS_KEY_ID" "SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> .env

      - run:
          name: Build
          command: tsc

      - run:
          name: Deploy
          command: sh bin/deploy.sh